export const AUTH_API_LOADING = '@AUTH/AUTH_API_LOADING';
export const AUTH_API_FAILED = '@AUTH/AUTH_API_FAILED';
export const CHANGE_LOGIN_STATE = '@AUTH/CHANGE_LOGIN_STATE';
export const LOGIN_SUCCESS = '@AUTH/LOGIN_SUCCESS';
export const REGISTER_SUCCESS = '@AUTH/REGISTER_SUCCESS';
export const REQUEST_FORGOT_PASSWORD_SUCCESS =
  '@AUTH/REQUEST_FORGOT_PASSWORD_SUCCESS';
export const VERIFY_RECOVERY_CODE_SUCCESS =
  '@AUTH/VERIFY_RECOVERY_CODE_SUCCESS';
export const RESET_PASSWORD_SUCCESS = '@AUTH/RESET_PASSWORD_SUCCESS';
export const ON_CHANGE_RECOVERY_EMAIL = '@AUTH/ON_CHANGE_RECOVERY_EMAIL';
export const LOG_OUT = '@AUTH/LOG_OUT';

export const CHARITY_API_LOADING = '@CHARITY/CHARITY_API_LOADING';
export const FAILED_CHARITY_API = '@CHARITY/FAILED_CHARITY_API';
export const SUCCESS_GET_ALL_CHARITIES = '@CHARITY/SUCCESS_GET_ALL_CHARITIES';
export const SELECT_CHARITY = '@CHARITY/SELECT_CHARITY';
export const SEARCH_CHARITIES = '@CHARITY/SEARCH_CHARITIES';
export const SUCCESS_GET_CHARITY_BY_ID = '@CHARITY/SUCCESS_GET_CHARITY_BY_ID';
export const SUCCESS_SELECT_CHARITY = '@CHARITY/SUCCESS_SELECT_CHARITY';
export const SUCCESS_REQUEST_CHARITY = '@CHARITY/SUCCESS_REQUEST_CHARITY';
export const SUCCESS_SET_DONATION_LEVEL = '@CHARITY/SUCCESS_SET_DONATION_LEVEL';

export const ACCOUNT_API_LOADING = '@ACCOUNT/ACCOUNT_API_LOADING';
export const ACCOUNT_API_FAILED = '@ACCOUNT/ACCOUNT_API_FAILED';
export const SUCCESS_GET_ALL_BANKS = '@ACCOUNT/SUCCESS_GET_ALL_BANKS';
export const SEARCH_BANKS = '@ACCOUNT/SEARCH_BANKS';
export const SUCCESS_GET_BANK_AUTH = '@ACCOUNT/SUCCESS_GET_BANK_AUTH';
export const SUCCESS_GET_MONEYHUB = '@ACCOUNT/SUCCESS_GET_MONEYHUB';
export const SUCCESS_CARD_REQUEST = '@ACCOUNT/SUCCESS_CARD_REQUEST';
export const SUCCESS_CARD_STATUS = '@ACCOUNT/SUCCESS_CARD_STATUS';

export const SETTINGS_API_LOADING = '@SETTINGS/SETTINGS_API_LOADING';
export const FAILED_SETTINGS_API = '@SETTINGS/FAILED_SETTINGS_API';
export const SUCCESS_CHARITY_REQUEST = '@SETTINGS/SUCCESS_CHARITY_REQUEST';
export const SUCCESS_ASK_QUESTION = '@SETTINGS/SUCCESS_ASK_QUESTION';
export const SUCCESS_LEAVE_FEEDBACK = '@SETTINGS/SUCCESS_LEAVE_FEEDBACK';
export const SUCCESS_CHANGE_PASSWORD = '@SETTINGS/SUCCESS_CHANGE_PASSWORD';
export const SUCCESS_UNLINK_MONEYHUB = '@SETTINGS/SUCCESS_UNLINK_MONEYHUB';
export const SUCCESS_GET_SETTINGS = '@SETTINGS/SUCCESS_GET_SETTINGS';

export const SUCCESS_REQUEST_DONATION_STATUS =
  '@DONATION/SUCCESS_REQUEST_DONATION_STATUS';
export const SUCCESS_RESCHEDULE_DONATION =
  '@DONATION/SUCCESS_RESCHEDULE_DONATION';